name: latex

on:
  push:
    branches:
      - 'master'
    paths:
      - 'latex/**'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: compile latex
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: latex/src/
          root_file: main.tex
          compiler: xelatex
      - name: upload pdf
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: latex/src/main.pdf
